# Generated by Django 3.1.7 on 2021-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', editable=False, max_length=12)),
                ('user_profileURL', models.URLField(blank=True, default='', max_length=100)),
                ('fcm', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
