# Generated by Django 3.1.7 on 2021-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210407_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
